---
title: "SOM_colourtest"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##Data Generation##############
set.seed(11)

# pick 2 main colors to act as cluster centers
col_label <- c("green","yellow")
r <- c(0, 240)
g <- c(158, 228)
b <- c(115, 66)
col_palette <- cbind.data.frame(r,g,b,col_label)
size <- c(10,20)
```

```{r}
##simulate similar color values around the 2 main colors###
d <- NULL
n <- 500
for (i in 1:length(col_label))  {
  sd <- size[i]
  r <- rnorm(n=n, mean=col_palette$r[i], sd=sd) #random normal dist
  g <- rnorm(n=n, mean=col_palette$g[i], sd=sd)
  b <- rnorm(n=n, mean=col_palette$b[i], sd=sd)
  label <- col_palette$col_label[i]

  # consolidate into dataset
  rgb <- cbind.data.frame(b,r,g,label)
  d <- rbind.data.frame(d,rgb) #to combine both the yellow df and green df, both of nrow() = 500
}

```

```{r}
# remove out-of-range RGB values
rgb_out <- which(d[,1:3]<0 | d[,1:3]>255, arr.ind = T)
rgb_out <- unique(rgb_out[,1]) #remove dups bc there might be dups across rows (either in r,g or b)
d <- d[-rgb_out,]
```

```{r}
# add hex values, more convenient to feed into R plotting commands
d$hex <- rgb(d$r, d$g, d$b, max=255)

# plot and save chosen colors
chosen_dim <- c(1,3)
plot(d[,chosen_dim],
     xlab = "Blue Value",
     ylab = "Green Value",
     col=d$hex, pch=16,
     ylim=c(130,255), xlim=c(0,150))
```

```{r}
# plot in 3D
library(scatterplot3d)
scatterplot3d(d[,1:3],
              color=d$hex, pch=20,
              col.grid="grey",
              xlab="Blue Value",
              ylab="Red Value",
              zlab="Green Value")
```

```{r}
# Data Analysis
#############################################

# install and load package
require(SOMbrero)

# set number of iterations
niter <- 200
#maxit= (nrow+ncol)*5; if not set

# train SOM
grid_dim <- 8 #typically m1=m2 = sqrt(n/10)
set.seed(11)
my.som <- SOMbrero::trainSOM(d[,1:3], dimension=c(grid_dim, grid_dim),
                   nb.save=niter/2, maxit=niter,radius.type="letremy") #author of paper;it is neighbourhood type, default is guassian, this is a piecewise linear neigbourhood; piece-wise linear fxs approximate to a continous fx
#nb.save = number of intermediate back-ups to be done during the algorithm process, default =0; the prototypes coordinates (bmus)are also registered for each intermediate backup so they can be displayed on different graphics to see the evolution in the prototypes organisation
```

```{r}
# plot convergence
plot(my.som, what="energy")
```

```{r}
# plot map on each iteration
npt <- grid_dim^2
steps <- my.som$backup$steps

for (s in 1:length(steps))  {

  # get neuron coordinates
  iterate_map <- my.som$backup$prototypes[[s]][,chosen_dim] #dim=(1,3), prototype = bmu; choose the blue and green dimensions; prototypes is a list of 100 lists, so index by [[]]

  # plot
  
```

```{r}
plot(d[,chosen_dim], col=d$hex,
       pch=16, cex=.5,
       main=paste('Iteration ', steps[s]),
       xlim=c(0,150),
       ylim=c(130,255))
  points(iterate_map) #the black dots are bmus or prototypes; 64 points

  for (pt in 1:npt) {

    # identify grid neighbors
    pt_neighbor <- c(pt-1,pt+1,
                     pt+grid_dim,pt-grid_dim)

    # remove out-of-range neighbors
    rm_out <- which(pt_neighbor < 1 | pt_neighbor > npt)

    # remove criss-cross links; don't want the lines to criss-cross together, makes     for messy visualisation; i think we are removing all pts that are +/- 1 from the     pt itself so that it doesn't generate a line that criss-crosses
    #if the 'pt' is a multiple of 8 or 9,17,25,33,41,49,57
    if ((pt %% grid_dim) == 0) {
      rm_crisscross <- which(pt_neighbor == (pt+1))
    }
    if ((pt %% grid_dim) == 1) {
      rm_crisscross <- which(pt_neighbor == (pt-1))
    }
    pt_neighbors <- pt_neighbor[-c(rm_out,rm_crisscross)]

    for(i in pt_neighbors)  {# i =1:2
      lines(x <- c(iterate_map[pt,1],iterate_map[i,1]), #pt=64,i=2
            y <- c(iterate_map[pt,2],iterate_map[i,2])) #pt=64,i=2
    }
  }
}
```

```{r}
# plot counts in each neuron
plot(my.som, what="obs", type="hitmap")
table(my.som$clustering)

```

```{r}
# radar plot for each neuron
plot(my.som, what="obs", type="radar",
     key.loc=c(-0.5,5), mar=c(0,10,2,0))
#legend location and margin
```

```{r}
# plot distance between neurons
plot(my.som, what="prototypes", type="smooth.dist")
```


```{r}
# label neurons with freq of color occurrence
# make dummy matrix
dummy1 <- as.numeric(d$label==levels(d$label)[1]) #green will be 1 yellow is 2
dummy2 <- as.numeric(d$label==levels(d$label)[2]) #yellow is 1 green is 2
dummy_labels <- cbind(dummy1, dummy2)
colnames(dummy_labels) <- levels(d$label)

```

```{r}
# plot
plot(my.som, what="add",
     type="words", variable=dummy_labels)
```

```{r}
# label neurons based on color prediction
plot(my.som, what="add",
     type="color", variable=dummy_labels[,1]) # based on what is green will be coloured red


```

```{r}
####################################################
# Clustering of Neurons
####################################################
#superClass - aggregates the resulting clustering of the SOm algorithm into super-clusters
my.clusters <- superClass(my.som, k=2) #k = # of clusters/classes; arg passed to the cutree fx which is the # of super-clusters
summary(my.clusters)
```

```{r}
plot(my.clusters, plot.var=FALSE) #a boolean indicating whether a graph showing the evolution of the explained variance should be plotted, used when type="dendrogram"
plot(my.clusters, type='grid', plot.legend=TRUE)
plot(my.clusters, type="hitmap", plot.legend=TRUE)
```

```{r}
####################################################
# Making Predictions
####################################################

library(kohonen)

# train model;#supersom wrapper fx with 2 layers
my.som2 <- xyf(scale(as.matrix(d[,1:3])), as.factor(d$label), 
               grid=somgrid(grid_dim, grid_dim, "rectangular"))

```

```{r}
# generate predictions
som.predictions <- predict(my.som2)

#unit.predictions - prediction values associated with the map units. Explicit definition of the predictions for each unit. return for each object the desired property associated with the corresponding winning unit (BMU). The averages of the winning units for the trainingdata will be used as unit.predictions

#predictions - predicated values for the proerties of interest (output data).
```


```{r}
# confusion matrix
table(som.predictions$predictions[[2]], d$label)

```

```{r}
# distance between data point and best matching unit (BMU)
# possible proxy for uncertainty
boxplot(my.som2$distances ~ d$label)
```

```{r}
# prediction for each neuron
som.predictions$unit.predictions
```
